/* const rcAiTopics = [
  {
    name: <ProgrammingFundamentals137 />,
    path: "programming-fundamentals-137",
  },
  {
    name: <BasicDataStructuresAndAlgorithms138 />,
    path: "basic-data-structures-and-algorithms-138",
  },
  {
    name: <ControlStructuresAndLoops139 />,
    path: "control-structures-and-loops-139",
  },
  { name: <FunctionsAndProcedures140 />, path: "functions-and-procedures-140" },
  { name: <OutputOperations141 />, path: "input-output-operations-141" },
  { name: <Mathematics142 />, path: "mathematics-142" },
  { name: <DifferentialCalculus143 />, path: "differential-calculus-143" },
  { name: <LimitsAndContinuity144 />, path: "limits-and-continuity-144" },
  { name: <Derivatives145 />, path: "derivatives-145" },
  { name: <Optimization146 />, path: "optimization-146" },
  { name: <IntegralCalculus147 />, path: "integral-calculus-147" },
  { name: <DefiniteIntegrals148 />, path: "definite-integrals-148" },
  { name: <IndefiniteIntegrals149 />, path: "indefinite-integrals-149" },
  { name: <AreasAndVolumes150 />, path: "areas-and-volumes-150" },
  { name: <DifferentialEquations151 />, path: "differential-equations-151" },
  { name: <MultivariableCalculus152 />, path: "multivariable-calculus-152" },
  { name: <PartialDerivatives153 />, path: "partial-derivatives-153" },
  {
    name: <GradientDivergenceAndCurl154 />,
    path: "gradient-divergence-and-curl-154",
  },
  {
    name: <DoubleAndTripleIntegrals155 />,
    path: "double-and-triple-integrals-155",
  },
  {
    name: <LineIntegralsAndSurfaceIntegrals156 />,
    path: "line-integrals-and-surface-integrals-156",
  },
  { name: <VectorsAndMatrices157 />, path: "vectors-and-matrices-157" },
  { name: <MatrixMultiplication158 />, path: "matrix-multiplication-158" },
  { name: <LinearTransformations159 />, path: "linear-transformations-159" },
  {
    name: <EigenvaluesAndEigenvectors160 />,
    path: "eigenvalues-and-eigenvectors-160",
  },
  { name: <ConvexOptimization161 />, path: "convex-optimization-161" },
  { name: <NonlinearOptimization162 />, path: "nonlinear-optimization-162" },
  { name: <GradientDescent163 />, path: "gradient-descent-163" },
  { name: <StochasticOptimization164 />, path: "stochastic-optimization-164" },
  { name: <ProbabilityTheory165 />, path: "probability-theory-165" },
  {
    name: <RandomVariablesAndDistributions166 />,
    path: "random-variables-and-distributions-166",
  },
  { name: <BayesTheorem167 />, path: "bayes-theorem-167" },
  { name: <DescriptiveStatistics168 />, path: "descriptive-statistics-168" },
  { name: <InferentialStatistics169 />, path: "inferential-statistics-169" },
  { name: <HypothesisTesting170 />, path: "hypothesis-testing-170" },
  { name: <RegressionAnalysis171 />, path: "regression-analysis-171" },
  { name: <Python172 />, path: "python-172" },
  { name: <Java173 />, path: "java-173" },
  { name: <C174 />, path: "c++-174" },
  { name: <JavaScript175 />, path: "javascript-175" },
  { name: <R176 />, path: "r-176" },
  { name: <PropositionalLogic177 />, path: "propositional-logic-177" },
  { name: <PropositionalVariables178 />, path: "propositional-variables-178" },
  { name: <LogicalConnectives179 />, path: "logical-connectives-179" },
  { name: <TruthTables180 />, path: "truth-tables-180" },
  { name: <PredicateLogic181 />, path: "predicate-logic-181" },
  { name: <Quantifiers182 />, path: "quantifiers-182" },
  { name: <Variables183 />, path: "variables-183" },
  { name: <Predicates184 />, path: "predicates-184" },
  { name: <LogicalEquivalence185 />, path: "logical-equivalence-185" },
  { name: <FirstOrderLogic186 />, path: "first-order-logic-186" },
  { name: <Terms187 />, path: "terms-187" },
  { name: <Formulas188 />, path: "formulas-188" },
  { name: <InferenceRules189 />, path: "inference-rules-189" },
  { name: <Soundness190 />, path: "soundness-190" },
  { name: <Completeness191 />, path: "completeness-191" },
  { name: <MachineLearningML192 />, path: "machine-learning-192" },
  { name: <SupervisedLearning193 />, path: "supervised-learning-193" },
  { name: <UnsupervisedLearning194 />, path: "unsupervised-learning-194" },
  { name: <SemiSupervisedLearning195 />, path: "semi-supervised-learning-195" },
  { name: <ReinforcementLearning196 />, path: "reinforcement-learning-196" },
  {
    name: <ConvolutionalNeuralNetworksCNN197 />,
    path: "convolutional-neural-networks-cnn-197",
  },
  {
    name: <RecurrentNeuralNetworksRNN198 />,
    path: "recurrent-neural-networks-rnn-198",
  },
  { name: <GenerativeModels199 />, path: "generative-models-199" },
  { name: <TextProcessing200 />, path: "text-processing-200" },
  { name: <LanguageModeling201 />, path: "language-modeling-201" },
  { name: <SyntaxAndParsing202 />, path: "syntax-and-parsing-202" },
  { name: <SentimentAnalysis203 />, path: "sentiment-analysis-203" },
  { name: <NamedEntityRecognition204 />, path: "named-entity-recognition-204" },
  { name: <MachineTranslation205 />, path: "machine-translation-205" },
  { name: <InformationExtraction206 />, path: "information-extraction-206" },
  { name: <TopicModeling207 />, path: "topic-modeling-207" },
  { name: <ImageProcessing208 />, path: "image-processing-208" },
  {
    name: <FeatureExtractionAndRepresentation209 />,
    path: "feature-extraction-and-representation-209",
  },
  {
    name: <ObjectRecognitionAndDetection210 />,
    path: "object-recognition-and-detection-210",
  },
  { name: <DeepLearningApproaches211 />, path: "deep-learning-approaches-211" },
  { name: <VideoAnalysis212 />, path: "video-analysis-212" },
  { name: <ThreeDComputerVision213 />, path: "3d-computer-vision-213" },
  {
    name: <OntologiesAndKnowledgeGraphs214 />,
    path: "ontologies-and-knowledge-graphs-214",
  },
  { name: <RDFOWLSPARQL215 />, path: "rdf-owl-sparql-215" },
  { name: <Reasoning216 />, path: "reasoning-216" },
  { name: <RuleBasedReasoning217 />, path: "rule-based-reasoning-217" },
  {
    name: <DescriptionLogicReasoning218 />,
    path: "description-logic-reasoning-218",
  },
  {
    name: <KnowledgeGraphEmbeddings219 />,
    path: "knowledge-graph-embeddings-219",
  },
  { name: <Robotics220 />, path: "robotics-220" },
  { name: <Perception221 />, path: "perception-221" },
  { name: <SensingAndMapping222 />, path: "sensing-and-mapping-222" },
  {
    name: <ObjectRecognitionAndTracking223 />,
    path: "object-recognition-and-tracking-223",
  },
  { name: <RobotKinematics224 />, path: "robot-kinematics-224" },
  { name: <RobotControl225 />, path: "robot-control-225" },
  { name: <RobotDynamics226 />, path: "robot-dynamics-226" },
  {
    name: <RobotPlanningAndNavigation227 />,
    path: "robot-planning-and-navigation-227",
  },
  {
    name: <RoboticsSoftwareDevelopment228 />,
    path: "robotics-software-development-228",
  },
  { name: <HumanRobotInteraction229 />, path: "human-robot-interaction-229" },
  {
    name: <RobotLearningAndReinforcementLearning230 />,
    path: "robot-learning-and-reinforcement-learning-230",
  },
  { name: <AIEthicsAndGovernance231 />, path: "ai-ethics-and-governance-231" },
  { name: <BiasAndFairness232 />, path: "bias-and-fairness-232" },
  {
    name: <AccountabilityAndTransparency233 />,
    path: "accountability-and-transparency-233",
  },
  { name: <PrivacyAndSecurity234 />, path: "privacy-and-security-234" },
  {
    name: <ArtificialIntelligenceApplications235 />,
    path: "artificial-intelligence-applications-235",
  },
  { name: <CareerPathsInAI236 />, path: "career-paths-in-ai-236" },
  {
    name: <MachineLearningEngineer237 />,
    path: "machine-learning-engineer-237",
  },
  { name: <DataScientist238 />, path: "data-scientist-238" },
  { name: <AIResearchScientist239 />, path: "ai-research-scientist-239" },
  { name: <NLPEngineer240 />, path: "nlp-engineer-240" },
  { name: <ComputerVisionEngineer241 />, path: "computer-vision-engineer-241" },
  { name: <RoboticsEngineer242 />, path: "robotics-engineer-242" },
  {
    name: <AIEthicsAndGovernanceSpecialist243 />,
    path: "ai-ethics-and-governance-specialist-243",
  },
  { name: <AIProductManager244 />, path: "ai-product-manager-244" },
  { name: <AIConsultant245 />, path: "ai-consultant-245" },
  { name: <Instructor246 />, path: "ai-trainer-instructor-246" },
  { name: <AIBusinessAnalyst247 />, path: "ai-business-analyst-247" },
  { name: <AITechnicalWriter248 />, path: "ai-technical-writer-248" },
  { name: <AIHardwareEngineer249 />, path: "ai-hardware-engineer-249" },
  {
    name: <AIQualityAssuranceEngineer250 />,
    path: "ai-quality-assurance-engineer-250",
  },
];
*/
