/* const frontendCombinedNameComponentPathArray = [
  { name: <Internet001 />, path: "internet-1" },
  { name: <HowDoesTheInternetWork002 />, path: "how-does-the-internet-work-2" },
  { name: <DNSAndHowItWorks003 />, path: "dns-and-how-it-works-3" },
  { name: <WhatIsHTTP004 />, path: "what-is-http-4" },
  { name: <WhatIsDomainName005 />, path: "what-is-domain-name-5" },
  { name: <BrowsersAndHowTheyWork006 />, path: "browsers-and-how-they-work-6" },
  { name: <WhatIsHosting007 />, path: "what-is-hosting-7" },
  { name: <HTML008 />, path: "html-8" },
  { name: <WritingSemanticHTML009 />, path: "html-writing-semantic-html-9" },
  { name: <HTMLFormAndValidation010 />, path: "html-form-and-validation-10" },
  { name: <HTMLWebAccessibility011 />, path: "html-web-accessibility-11" },
  { name: <HTMLSEOBasics012 />, path: "html-seo-basics-12" },
  { name: <CSS013 />, path: "css-13" },
  { name: <CSSMakingLayouts014 />, path: "css-making-layouts-14" },
  { name: <CSSLearnTheBasics015 />, path: "css-learn-the-basics-15" },
  { name: <CSSSelectors016 />, path: "css-selectors-16" },
  { name: <CSSColors017 />, path: "css-colors-17" },
  { name: <CSSTypography018 />, path: "css-typography-18" },
  { name: <CSSBoxModel019 />, path: "css-box-model-19" },
  { name: <JavaScript020 />, path: "javascript-20" },
  {
    name: <JavaScriptSyntaxBasicsConstructs021 />,
    path: "javascript-syntax-and-basics-constructs-21",
  },
  { name: <LearnDOMManipulation022 />, path: "learn-dom-manipulation-22" },
  { name: <LearnAjaxAndAPIs023 />, path: "learn-ajax-and-apis-23" },
  {
    name: <ES6AndModularJavaScript024 />,
    path: "es6-and-modular-javascript-24",
  },
  { name: <UnderstandTheConcepts025 />, path: "understand-the-concepts-25" },
  { name: <VersionControlSystems026 />, path: "version-control-systems-26" },
  {
    name: <VCSBasicCommand027 />,
    path: "version-control-systems-basic-command-27",
  },
  { name: <VCSBranching028 />, path: "version-control-systems-branching-28" },
  { name: <VCSMerging029 />, path: "version-control-systems-merging-29" },
  {
    name: <RepoHostinigServiceGithub030 />,
    path: "repo-hosting-service-github-30",
  },
  {
    name: <RepoHostinigServiceGitLab031 />,
    path: "repo-hosting-service-gitlab-31",
  },
  {
    name: <RepoHostinigServiceBitbucket032 />,
    path: "repo-hosting-service-bitbucket-32",
  },
  { name: <HTTPS033 />, path: "web-security-knowledge-https-33" },
  {
    name: <ContentSecurityPolicy034 />,
    path: "web-security-knowledge-content-security-policy-34",
  },
  { name: <CORS035 />, path: "web-security-knowledge-cors-35" },
  {
    name: <OWASPSecurityRisks036 />,
    path: "web-security-knowledge-owasp-security-risks-36",
  },
  { name: <PackageManagersNpm037 />, path: "package-managers-npm-37" },
  { name: <PackageManagersYarn038 />, path: "package-managers-yarn-38" },
  { name: <PackageManagersPnpm039 />, path: "package-managers-pnpm-39" },
  { name: <BEMBlockElementModifier040 />, path: "css-architecture-bem-40" },
  { name: <Sass041 />, path: "css-preprocessors-sass-41" },
  { name: <Less042 />, path: "css-preprocessors-less-42" },
  { name: <PostCSS043 />, path: "css-preprocessors-postcss-43" },
  {
    name: <HigherorderFunctions044 />,
    path: "advance-javascript-higher-order-functions-44",
  },
  { name: <Closures045 />, path: "advance-javascript-closures-45" },
  { name: <Await046 />, path: "advance-javascript-promises-async-await-46" },
  {
    name: <EventLoopConcurrency047 />,
    path: "advance-javascript-event-loop-concurrency-47",
  },
  {
    name: <PerformanceOptimization048 />,
    path: "advance-javascript-performance-optimization-48",
  },
  { name: <Classes049 />, path: "advance-javascript-classes-49" },
  { name: <Prototypes050 />, path: "advance-javascript-prototypes-50" },
  { name: <Inheritance051 />, path: "advance-javascript-inheritance-51" },
  {
    name: <BuildToolsLintersAndFormatters052 />,
    path: "build-tools-linters-and-formatters-52",
  },
  { name: <BuildToolsPrettier053 />, path: "build-tools-prettier-53" },
  { name: <BuildToolsESLint054 />, path: "build-tools-eslint-54" },
  { name: <BuildToolsTaskRunners055 />, path: "build-tools-task-runners-55" },
  { name: <BuildToolsNpmScripts056 />, path: "build-tools-npm-scripts-56" },
  {
    name: <ModuleBundlersVite057 />,
    path: "build-tools-module-bundlers-vite-57",
  },
  {
    name: <ModuleBundlersEsbuild058 />,
    path: "build-tools-module-bundlers-esbuild-58",
  },
  {
    name: <ModuleBundlersWebpack059 />,
    path: "build-tools-module-bundlers-webpack-59",
  },
  {
    name: <ModuleBundlersRollup060 />,
    path: "build-tools-module-bundlers-rollup-60",
  },
  {
    name: <ModuleBundlersParcel061 />,
    path: "build-tools-module-bundlers-parcel-61",
  },
  { name: <React062 />, path: "pick-a-framework-react-62" },
  { name: <Angular063 />, path: "pick-a-framework-angular-63" },
  { name: <Vuejs064 />, path: "pick-a-framework-vuejs-64" },
  { name: <Svelte065 />, path: "pick-a-framework-svelte-65" },
  { name: <SolidJS066 />, path: "pick-a-framework-solid-js-66" },
  { name: <StyledComponents067 />, path: "modern-css-styled-components-67" },
  { name: <CSSModules068 />, path: "modern-css-css-modules-68" },
  { name: <StyledJSX069 />, path: "modern-css-styled-jsx-69" },
  { name: <Emotion070 />, path: "modern-css-emotion-70" },
  { name: <Mantine071 />, path: "css-frameworks-mantine-71" },
  { name: <Tailwind072 />, path: "css-frameworks-tailwind-72" },
  { name: <ChakraUI073 />, path: "css-frameworks-chakra-ui-73" },
  { name: <MaterialUI074 />, path: "css-frameworks-material-ui-74" },
  { name: <DaisyUI075 />, path: "css-frameworks-daisyui-75" },
  { name: <RadixUI076 />, path: "css-frameworks-radix-ui-76" },
  { name: <Bootstrap077 />, path: "css-frameworks-bootstrap-77" },
  { name: <Bulma078 />, path: "css-frameworks-bulma-78" },
  { name: <TestingYourApps079 />, path: "testing-your-apps-79" },
  { name: <Jest080 />, path: "testing-your-apps-jest-80" },
  {
    name: <Reacttestinglibrary081 />,
    path: "testing-your-apps-react-testing-library-81",
  },
  { name: <Cypress082 />, path: "testing-your-apps-cypress-82" },
  { name: <Playwright083 />, path: "testing-your-apps-playwright-83" },
  {
    name: <AuthenticationStrategies084 />,
    path: "authentication-strategies-84",
  },
  { name: <WebComponents085 />, path: "web-components-85" },
  { name: <HTMLTemplates086 />, path: "wc-html-templates-86" },
  { name: <CustomElements087 />, path: "wc-custom-elements-87" },
  { name: <ShadowDOM088 />, path: "wc-shadow-dom-88" },
  { name: <TypeCheckerTypeScript089 />, path: "type-checker-typescript-89" },
  { name: <Storage090 />, path: "pwa-storage-90" },
  { name: <WebSockets091 />, path: "pwa-web-sockets-91" },
  { name: <PServerSentEvents092 />, path: "pwa-server-sent-events-92" },
  { name: <ServiceWorkers093 />, path: "pwa-service-workers-93" },
  { name: <Location094 />, path: "pwa-location-94" },
  { name: <Notifications095 />, path: "pwa-notifications-95" },
  { name: <DeviceOrientation096 />, path: "pwa-device-orientation-96" },
  { name: <Payments097 />, path: "pwa-payments-97" },
  { name: <Credentials098 />, path: "pwa-credentials-98" },
  { name: <PRPLPattern099 />, path: "prpl-pattern-99" },
  { name: <RAILModel100 />, path: "rail-model-100" },
  { name: <PerformanceMetrics101 />, path: "performance-metrics-101" },
  { name: <UsingLighthouse102 />, path: "using-lighthouse-102" },
  { name: <UsingDevTools103 />, path: "using-devtools-103" },
  {
    name: <ServerSideRenderingSSR104 />,
    path: "server-side-rendering-ssr-104",
  },
  { name: <React105 />, path: "react-server-side-rendering-ssr-105" },
  { name: <Angular106 />, path: "angular-server-side-rendering-ssr-106" },
  { name: <Vuejs107 />, path: "vuejs-server-side-rendering-ssr-107" },
  { name: <Svelte108 />, path: "svelte-server-side-rendering-ssr-108" },
  { name: <Remix109 />, path: "remix-server-side-rendering-ssr-109" },
  { name: <Nextjs110 />, path: "nextjs-server-side-rendering-ssr-110" },
  { name: <Universal111 />, path: "universal-server-side-rendering-ssr-111" },
  { name: <Nuxtjs112 />, path: "nuxtjs-server-side-rendering-ssr-112" },
  { name: <SvelteKit113 />, path: "svelte-kit-server-side-rendering-ssr-113" },
  { name: <StaticSiteGenerators114 />, path: "static-site-generators-114" },
  { name: <Eleventy115 />, path: "eleventy-static-site-generation-115" },
  { name: <Astro116 />, path: "astro-static-site-generation-116" },
  { name: <Nextjs117 />, path: "nextjs-static-site-generation-117" },
  { name: <GatsbyJS118 />, path: "gatsbyjs-static-site-generation-118" },
  { name: <Vuepress119 />, path: "vuepress-static-site-generation-119" },
  { name: <Jekyll120 />, path: "jekyll-static-site-generation-120" },
  { name: <Hugo121 />, path: "hugo-static-site-generation-121" },
  { name: <Nuxtjs122 />, path: "nuxtjs-static-site-generation-122" },
  { name: <Remix123 />, path: "remix-server-side-generation-123" },
  { name: <SvelteKit124 />, path: "svelte-kit-server-side-rendering-ssr-124" },
  { name: <GraphQL125 />, path: "graphql-125" },
  { name: <Apollo126 />, path: "apollo-graph-126" },
  { name: <RelayModern127 />, path: "relay-modern-graphql-127" },
  {
    name: <MobileApplications128 />,
    path: "mobile-applications-react-native-128",
  },
  { name: <ReactNative129 />, path: "mobile-applications-react-native-129" },
  { name: <Flutter130 />, path: "mobile-applications-flutter-130" },
  { name: <Ionic131 />, path: "mobile-applications-ionic-131" },
  { name: <NativeScript132 />, path: "mobile-applications-nativescript-132" },
  {
    name: <DesktopApplications133 />,
    path: "desktop-applications-electron-133",
  },
  { name: <Electron134 />, path: "desktop-applications-electron-134" },
  { name: <Tauri135 />, path: "desktop-applications-tauri-135" },
  { name: <Flutter136 />, path: "desktop-applications-flutter-136" },
];
export {frontendCombinedNameComponentPathArray} */
